package br.com.meirelesefreitas.go.checkonline.ui.theme

import androidx.compose.ui.graphics.Color

// Expressive Green Material 3 Palette - Light
val md_theme_light_primary = Color(0xFF006D3B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF98F7B3)
val md_theme_light_onPrimaryContainer = Color(0xFF00210E)
val md_theme_light_secondary = Color(0xFF4F6353)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD2E8D4)
val md_theme_light_onSecondaryContainer = Color(0xFF0D1F13)
val md_theme_light_tertiary = Color(0xFF3B6471)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBEEAF8)
val md_theme_light_onTertiaryContainer = Color(0xFF001F27)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF7FBF4)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFF7FBF4)
val md_theme_light_onSurface = Color(0xFF191C1A)
val md_theme_light_surfaceVariant = Color(0xFFDDE5DC)
val md_theme_light_onSurfaceVariant = Color(0xFF414942)
val md_theme_light_outline = Color(0xFF717972)
val md_theme_light_outlineVariant = Color(0xFFC1C9C0)
val md_theme_light_scrim = Color(0xFF000000)

// Expressive Green Material 3 Palette - Dark
val md_theme_dark_primary = Color(0xFF7CDA99)
val md_theme_dark_onPrimary = Color(0xFF00391C)
val md_theme_dark_primaryContainer = Color(0xFF00532B)
val md_theme_dark_onPrimaryContainer = Color(0xFF98F7B3)
val md_theme_dark_secondary = Color(0xFFB6CCB9)
val md_theme_dark_onSecondary = Color(0xFF223527)
val md_theme_dark_secondaryContainer = Color(0xFF384B3C)
val md_theme_dark_onSecondaryContainer = Color(0xFFD2E8D4)
val md_theme_dark_tertiary = Color(0xFFA2CEDB)
val md_theme_dark_onTertiary = Color(0xFF033541)
val md_theme_dark_tertiaryContainer = Color(0xFF214C58)
val md_theme_dark_onTertiaryContainer = Color(0xFFBEEAF8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF111412)
val md_theme_dark_onBackground = Color(0xFFE2E3DF)
val md_theme_dark_surface = Color(0xFF111412)
val md_theme_dark_onSurface = Color(0xFFE2E3DF)
val md_theme_dark_surfaceVariant = Color(0xFF414942)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9C0)
val md_theme_dark_outline = Color(0xFF8B938B)
val md_theme_dark_outlineVariant = Color(0xFF414942)
val md_theme_dark_scrim = Color(0xFF000000)

// Brand Banner & Accent Colors
val BannerGradientStart = Color(0xFF004D27)
val BannerGradientMiddle = Color(0xFF007A40)
val BannerGradientEnd = Color(0xFF10A861)
val BannerWaveLine1 = Color(0x55A5F3C6)
val BannerWaveLine2 = Color(0x33D1FAE5)

val ExpressiveSuccess = Color(0xFF1E8E3E)
val ExpressiveSuccessContainer = Color(0xFFCEEAD6)
val ExpressiveWarning = Color(0xFFE37400)
val ExpressiveWarningContainer = Color(0xFFFEEFC3)
val ExpressiveError = Color(0xFFD93025)
val ExpressiveErrorContainer = Color(0xFFFAD2CF)
val ExpressiveInfo = Color(0xFF1A73E8)
val ExpressiveInfoContainer = Color(0xFFD2E3FC)